emulators:
  enabled:
  - 2
functions:
  building: true
  coop: false
  feeding_zone: true
  mail_rewards: false
  ponds: true
  prime_times: false
  research: false
  shield: false
  tiles: false
  wilds: false
settings:
  max_concurrent: 2
