emulators:
  enabled:
  - 0
functions:
  building: false
  coop: false
  feeding_zone: false
  mail_rewards: false
  ponds: false
  prime_times: false
  research: true
  shield: false
  tiles: false
  wilds: false
settings:
  max_concurrent: 2
